#!/bin/sh

#Script for Debian fresh install. Execute as root
# Tested functional september 17

# Modify /etc/apt/sources.list file for debian 11. Includes non free repos. 
echo "deb http://deb.debian.org/debian buster main contrib non-free" > /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian buster main contrib non-free" >> /etc/apt/sources.list
echo "" >> /etc/apt/sources.list
echo "deb http://security.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://security.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list
echo "" >> /etc/apt/sources.list
echo "deb http://deb.debian.org/debian buster-updates main contrib non-free" >> /etc/apt/sources.list
echo "deb-src http://deb.debian.org/debian buster-updates main contrib non-free" >> /etc/apt/sources.list
echo "" >> /etc/apt/sources.list
echo "# Visit https://wiki.debian.org/SourcesList for more info." >> /etc/apt/sources.list

# update upgrade
apt update
apt dist-upgrade -y
apt autoremove -y

# remove unwanted apps (feel free to modify)

apt purge evolution libreoffice-core gnome-nibbles \
gnome-tetravex gnome-taquin tali swell-foop five-or-more \
gnome-mines gnome-robots quadrapassel hitori gnome-2048 \
aisleriot iagno gnome-klotski lightsoff four-in-a-row gnome-mahjongg -y
apt autoremove -y

#remove conflicting package
#apt --purge remove libva2 -y

apt update
apt dist-upgrade -y
apt autoremove -y

#install useful apps (fell free to modify)
apt install pavucontrol \
gcc git fish vim curl \
zsh gnome-tweak-tool \
obs-studio vlc transmission flatpak \
firmware-linux blueman firmware-iwlwifi \
bridge-utils tlp tlp-rdw -y
# configure flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#mediawriter
echo "installing fedora media writer"
flatpak install flathub org.fedoraproject.MediaWriter -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.gnome.Evolution -y

# Enable laptop battery saver service. 
systemctl start tlp
systemctl enable tlp

# Home username variable
home_user_name=$(ls /home/ | grep -wv admin)

# Configure BASHRC and home/user/bin
echo "Configuring home user bin directory"

cat <<EOT >> /home/$home_user_name/.bashrc
export PATH="/home/$(ls /home/ | grep -wv admin)/bin:$PATH"
EOT

source /home/$home_user_name/.bashrc
mkdir /home/$home_user_name/bin
chown -R $home_user_name:$home_user_name /home/$home_user_name/bin

echo "configuring touchpy"
touch /home/$home_user_name/bin/pytouch
chown $home_user_name:$home_user_name /home/$home_user_name/bin/pytouch
chmod +x /home/$home_user_name/bin/pytouch

cat <<EOT >> /home/$home_user_name/bin/pytouch
#!/usr/bin/env python3
import os, sys

try:
    filename = sys.argv[2]
    flag = sys.argv[1]
except:
    #Note: error type can make this piece of code work or not. 
    print("Please include params -s for sh, -p for python")
    #main function checks if the variable named 'flags' exists in global variables

def createpy():
    file_ext = ".py"
    with open("{}{}".format(filename,file_ext), "w") as file:
        file.write("#!/usr/bin/env python3\n")
        file.write("\n")
        file.write("def main():")
        file.write("\n\n")
        file.write("main()\n")

    final_name= "{}{}".format(filename,file_ext)
    os.chmod(final_name,0o755)
    print("File {} has been created".format(final_name))
    file.close()

def createpy_main():
    file_ext = ".py"
    with open("{}{}".format(filename,file_ext), "w") as file:
        file.write("#!/usr/bin/env python3\n")
        file.write("\n")
        file.write("def main():")
        file.write("\n\n\n\n")
        file.write("if __name__ == '__main__':")
        file.write("\n\tmain()")


    final_name= "{}{}".format(filename,file_ext)
    os.chmod(final_name,0o755)
    print("File {} has been created".format(final_name))
    file.close()

def createbash():
    file_ext = ".sh"
    with open("{}{}".format(filename,file_ext), "w") as file:
        file.write("#!/bin/sh\n")
    final_name= "{}{}".format(filename,file_ext)
    os.chmod(final_name,0o755)
    print("File {} has been created".format(final_name))
    file.close()

def createc():
  
    file_ext = ".c"

    with open("{}{}".format(filename,file_ext), "w") as file:
        file.write("#include <stdio.h>\n")
        file.write("#include <stdlib.h>\n")
        file.write("\n")
        file.write("int main(void){\n")
        file.write("\tputs(\"Hello, world!\");\n")
        file.write("\treturn EXIT_SUCCESS;\n")
        file.write("}\n")

    final_name = "{}{}".format(filename,file_ext)
    print("File {} has been created".format(final_name))
    file.close()
    
def creation():
    """this script creates a .py or .sh file based on flags passed when exec    uted (-p or -s).Each file will be created with execute permissions and inside of each file, the first line wille include a shebang #! line argument"""
    
    file_ext = ""

    if flag == '-p':
        createpy()
    elif flag == '-s':
        createbash()
    elif flag == '-c':
        createc()
    else:
        print("Invalid Input")

def main():
    if 'flag' and 'filename' in globals(): 
        creation()
    else:
        print("",end='')
main()
EOT

echo "Success. Script completed."


# Block distracting websites. Modify as needed. 

echo "# Facebook" >> /etc/hosts
echo "127.0.0.1   www.facebook.com" >> /etc/hosts
echo "127.0.0.1   facebook.com" >> /etc/hosts
echo "127.0.0.1   login.facebook.com" >> /etc/hosts
echo "127.0.0.1   www.login.facebook.com" >> /etc/hosts
echo "127.0.0.1   fbcdn.net" >> /etc/hosts
echo "127.0.0.1   www.fbcdn.net" >> /etc/hosts
echo "127.0.0.1   fbcdn.com" >> /etc/hosts
echo "127.0.0.1   www.fbcdn.com" >> /etc/hosts
echo "127.0.0.1   static.ak.fbcdn.net" >> /etc/hosts
echo "127.0.0.1   static.ak.connect.facebook.com" >> /etc/hosts
echo "127.0.0.1   connect.facebook.net" >> /etc/hosts
echo "127.0.0.1   www.connect.facebook.net" >> /etc/hosts
echo "127.0.0.1   apps.facebook.com" >> /etc/hosts
echo "0.0.0.0     meta.com" >> /etc/hosts
echo "0.0.0.0     www.meta.com" >> /etc/hosts
echo "# Twitter" >> /etc/hosts
echo "127.0.0.1   www.twitter.com" >> /etc/hosts
echo "127.0.0.1   twitter.com" >> /etc/hosts
echo "# IG" >> /etc/hosts
echo "127.0.0.1   instagram.com" >> /etc/hosts
echo "127.0.0.1   www.instagram.com" >> /etc/hosts
echo "#Amazon" >> /etc/hosts
echo "127.0.0.1   www.amazon.com" >> /etc/hosts
echo "127.0.0.1   amazon.com" >> /etc/hosts
echo "# Wasap" >> /etc/hosts
echo "127.0.0.1   web.whatsapp.com" >> /etc/hosts
